### ISSUE TITLE
Leader isn't passed through to the app when the timeout expires

### ISSUE THREAD

**Issue by mpe** [michaelbeaumont/awesome-leader#1]
I wanted to use `'` (apostrophe) as my leader.

But sometimes I need to actually use that to insert an apostrophe.

I was hoping if I just let the timeout expire (1 second) then the `'` would be passed through to the application. But that doesn't happen.

Looking at the code I don't see anything that looks like it even tries to do that (though my Lua is _poor_).

Is that just impossible to do? Or not something you thought of?

**Comment by michaelbeaumont** [comment]
Hey!

This is something I really wanted as well! There's an issue at the awesome repo awesomewm/awesome#77 about trying to solve the basic issue.

It's due to how X and awesome grab the keyboard for a certain key. The problem is that once the `'` is bound, it will always activate the function you've passed to it, anytime the key is sent. So after your timeout expires and you try to pass `'`, your passed function is called again. It's not possible to "go around" grabbing a key by faking a key press.

One option _seems_ to be to ungrab the keyboard, pass the `'` key and then regrab the keyboard. But the timing of all of these actions doesn't really happen smoothly, and very often the keypresses are still lost.
I.e. if I wanted to type `''` quickly, both apostrophes won't be registered most of the time.

**Comment by mpe** [comment]
OK thanks.

I read that bug previously and figured it was related, but wasn't clear if you had figured out a solution. 

Feel free to close this issue. Thanks.
